image: node:12.13.0
definitions:
  steps:
    - step: &mirror
        name: Mirror
        script:
          - chmod +x ./scripts/mirror.sh
          - ./scripts/mirror.sh
    - step: &lint
        name: Lint
        caches:
          - node
        script:
          - npm install
          - npm run lint
    - step: &test-unit
        name: Unit Tests
        caches:
          - node
        script:
          - npm install
          - npm run cover:unit
        artifacts:
          - coverage/**
          - .nyc_output/**
    - step: &test-integration
        name: Integration Tests
        caches:
          - node
          - cypress
        image: cypress/base:10
        script:
          - npm install
          - npm run cover:integration
        artifacts:
          - coverage-cypress/**
          - .nyc_output/**
    - step: &build
        name: Build
        caches:
          - npm
        script:
          - npm install
          - npm run build
    - step: &clean-coverage
        name: Reset coverage
        script:
          - npm run cover:clean
        artifacts:
          - coverage/**
          - .nyc_output/**
    - step: &coverage
        name: App coverage
        caches:
          - npm
        script:
          - npm install
          - npm run cover:merge
          - npm run cover:report
        artifacts:
          - coverage/lcov-report/**
  caches:
    node: $HOME/.npm
    cypress: $HOME/.cache/Cypress
pipelines:
default:
    - step: *clean-coverage
    - parallel:
        - step: *lint
        - step: *test-unit
        - step: *test-integration
        - step: *build
    - step: *coverage
  branches:
    master:
      - step: *clean-coverage
      - parallel:
          - step: *lint
          - step: *test-unit
          - step: *test-integration
      - parallel:
          - step: *coverage
          - step: *mirror
          - step: *build